// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_circle_i_level_14__deaths = "CgkItbv2qIoDEAIQHQ"; // <GPGSID>
        public const string leaderboard_circle_i_level_1__best_time = "CgkItbv2qIoDEAIQAQ"; // <GPGSID>
        public const string leaderboard_circle_i_level_9__best_time = "CgkItbv2qIoDEAIQCQ"; // <GPGSID>
        public const string leaderboard_circle_i_level_6__deaths = "CgkItbv2qIoDEAIQFQ"; // <GPGSID>
        public const string leaderboard_circle_i_level_5__deaths = "CgkItbv2qIoDEAIQFA"; // <GPGSID>
        public const string leaderboard_circle_i_level_2__best_time = "CgkItbv2qIoDEAIQAg"; // <GPGSID>
        public const string leaderboard_circle_i_level_13__deaths = "CgkItbv2qIoDEAIQHA"; // <GPGSID>
        public const string leaderboard_circle_i_level_11__best_time = "CgkItbv2qIoDEAIQCw"; // <GPGSID>
        public const string leaderboard_circle_i_level_3__best_time = "CgkItbv2qIoDEAIQAw"; // <GPGSID>
        public const string leaderboard_circle_i_level_4__deaths = "CgkItbv2qIoDEAIQEw"; // <GPGSID>
        public const string leaderboard_circle_i_level_12__best_time = "CgkItbv2qIoDEAIQDA"; // <GPGSID>
        public const string leaderboard_circle_i_level_12__deaths = "CgkItbv2qIoDEAIQGw"; // <GPGSID>
        public const string leaderboard_circle_i_level_4__best_time = "CgkItbv2qIoDEAIQBA"; // <GPGSID>
        public const string leaderboard_circle_i_level_13__best_time = "CgkItbv2qIoDEAIQDQ"; // <GPGSID>
        public const string leaderboard_circle_i_level_9__deaths = "CgkItbv2qIoDEAIQGA"; // <GPGSID>
        public const string leaderboard_circle_i_level_7__deaths = "CgkItbv2qIoDEAIQFg"; // <GPGSID>
        public const string leaderboard_circle_i_level_11__deaths = "CgkItbv2qIoDEAIQGg"; // <GPGSID>
        public const string leaderboard_circle_i_level_10__deaths = "CgkItbv2qIoDEAIQGQ"; // <GPGSID>
        public const string leaderboard_circle_i_level_14__best_time = "CgkItbv2qIoDEAIQDg"; // <GPGSID>
        public const string leaderboard_circle_i_level_6__best_time = "CgkItbv2qIoDEAIQBg"; // <GPGSID>
        public const string leaderboard_circle_i_level_5__best_time = "CgkItbv2qIoDEAIQBQ"; // <GPGSID>
        public const string leaderboard_circle_i_level_8__deaths = "CgkItbv2qIoDEAIQFw"; // <GPGSID>
        public const string leaderboard_circle_i_level_3__deaths = "CgkItbv2qIoDEAIQEg"; // <GPGSID>
        public const string leaderboard_circle_i_level_15__best_time = "CgkItbv2qIoDEAIQDw"; // <GPGSID>
        public const string leaderboard_circle_i_level_7__best_time = "CgkItbv2qIoDEAIQBw"; // <GPGSID>
        public const string leaderboard_circle_i_level_15__deaths = "CgkItbv2qIoDEAIQHg"; // <GPGSID>
        public const string leaderboard_circle_i_level_2__deaths = "CgkItbv2qIoDEAIQEQ"; // <GPGSID>
        public const string leaderboard_circle_i_level_1__deaths = "CgkItbv2qIoDEAIQEA"; // <GPGSID>
        public const string leaderboard_circle_i_level_8__best_time = "CgkItbv2qIoDEAIQCA"; // <GPGSID>
        public const string leaderboard_circle_i_level_10__best_time = "CgkItbv2qIoDEAIQCg"; // <GPGSID>

}

